name: Update Configs

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  

    - name: List directory structure
      run: |
        pwd
        ls -la
        ls -la Files || echo "Files directory not found"
        ls -la Files/app.py || echo "app.py not found"
      continue-on-error: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd Files || exit 1
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 jdatetime pytz
      continue-on-error: false

    - name: Run Python script
      run: |
        cd Files || exit 1
        python app.py
      continue-on-error: false

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "tahmaseb73"
        author_email: "tahmaseb73@example.com"
        message: "Update configs by tahmaseb73_ConfigScavenger"
        add: "Files/*" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
